# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.tapt


from PyQt5 import QtCore, QtWidgets

X = 0
Y = 0


class ControlPanel(QtWidgets.QMainWindow):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.init_gui()

    def init_gui(self):
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(TitleBar(self))
        self.setLayout(self.layout)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.addStretch(-1)
        self.setFixedSize(800, 480)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setObjectName("control_panel")

        # self.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(153, 170, 181, 255), stop:0.431818 rgba(153, 170, 181, 255), stop:0.727273 rgba(100, 110, 117, 255), stop:0.965909 rgba(44, 47, 51, 255), stop:1 rgba(35, 39, 42, 255));")



    def mouseMoveEvent(self, event):
        super(ControlPanel, self).mouseMoveEvent(event)
        if self.leftClick == True:
            self.move(event.globalPos().x() - X, event.globalPos().y() - Y)

    def mousePressEvent(self, event):
        if event.pos().y() <= 30:
            super(ControlPanel, self).mousePressEvent(event)
            if event.button() == QtCore.Qt.LeftButton:
                self.leftClick = True
                global X, Y
                X = event.pos().x()
                Y = event.pos().y()

    def mouseReleaseEvent(self, event):
        super(ControlPanel, self).mouseReleaseEvent(event)
        self.leftClick = False


class TitleBar(QtWidgets.QWidget):
    def __init__(self, parent):
        super(TitleBar, self).__init__()
        self.parent = parent
        self.setStyleSheet("background-color: rgb(30, 34, 36);")
        self.layout = QtWidgets.QHBoxLayout()
        self.layout.setContentsMargins(0, 0, 0, 0)

        self.title = QtWidgets.QLabel("Temperature Control Panel")
        self.title.setObjectName("title")
        self.title.setFixedSize(260, 30)
        self.title.setStyleSheet("""
            font: 87 14pt Segoe UI Black;"
            color: rgb(255, 255, 255);"
            background-color: rgb(30, 34, 36);""")

        self.layout.addWidget(self.title)
        self.setLayout(self.layout)