# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class control_panel(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(control_panel, self).__init__(parent)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setObjectName("control_panel")
        self.setFixedSize(800, 480)


